### PR TITLE
Make Property... (PropertyString etc.) to templates

### PR DESCRIPTION
**Pull request by lanice**
This equalizes the implementation of supported Property types, and makes PropertyString, PropertyBool, PropertyColor, PropertyFilePath, to template classes.

This also adds std::string as datatype for Property instanciation testing.

### CODE REVIEW

**Comment by cgcostume** [comment]
Please remove ```REFLECTIONZEUG_API``` from ```PropertyFilePath```, ```PropertyColor```, ```PropertyString```, and ```PropertyBool```. With this change, libzeug compiles on windows - the latest commit 5a998f63c405f9267c34b9882cec902dac066124 is obsolete then, so we should revert before merge.

**Comment by lanice** [comment]
Reverted commit 5a998f6 and removed REFLECTIONZEUG_API from PropertyFilePath, PropertyColor, PropertyString, and PropertyBool. Compiles on Ubuntu 14.04 with gcc 4.8.

**Comment by scheibel** [comment]
Now we have two reverts of this commit. One in master and another in this branch... can you merge the libzeug master just to make sure nothing confusing happens?

**Comment by lanice** [comment]
Done.

**Pull request merged**
